version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      COURSES_MONGO_URI: 'mongodb://mongo:27017'
      COURSES_MONGO_DB: 'courses'
  mongo:
    image: mongo